name: PythonCI
  
on:
  push:
  pull_request:  
  
jobs:  
  run-tests:  
    strategy: 
      fail-fast: false 
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        python-version: ["3.8", "3.9", "3.10"]  
    name: Test
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Setup python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Remove folder qsee
        uses: JesseTG/rm@v1.0.3
        with:
          path: qsee
      - name: Install dependecies
        run: |
          pip install -r requirements.txt
          git clone https://github.com/vutuanhai237/qsee.git
      - name: Run testcases
        run: |
          cd test
          python -m pytest